[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [ "img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "244", "-f", "Nearest",]
set = true

####################################################################

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.swaync]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

####################################################################

[templates.tty]
input_path = "./templates/tty-colors.sh.tpl"
output_path = "~/.cache/matugen/tty_colors.sh"

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

####################################################################

# --- GTK3 & GTK4 Theming --- # Breeze needed

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme Breeze-Dark'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# --- Qt5 & Qt6 Theming ---

[templates.qt]
input_path = './templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
