[config]
reload_apps = true

[config.wallpaper]
command = "awww"
arguments = [ "img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "244", "-f", "Nearest",]
set = true

####################################################################

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/0_session/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/css-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar && waybar >/dev/null 2>&1 &'

[templates.swaync]
input_path = './templates/css-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client --reload-css'

[templates.wlogout]
input_path = './templates/css-colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.tty]
input_path = "./templates/tty-colors.tpl"
output_path = "~/.cache/matugen/tty_colors"
post_hook = 'source ~/.zshrc'

[templates.vicinae]
input_path = "./templates/vicinae-colors.toml"
output_path = "~/.local/share/vicinae/themes/matugen.toml"
post_hook = 'vicinae theme set matugen'

[templates.ghostty]
input_path = "./templates/ghostty-colors.tpl"
output_path = "~/.config/ghostty/themes/matugen"

####################################################################

# --- GTK3 & GTK4 Theming --- # needs breeze breeze5 breeze-icons breeze-gtk qt6ct-kde qt5ct-kde

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme Breeze'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# --- Qt5 & Qt6 Theming ---

[templates.qt]
input_path = './templates/qt.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
