source = ./../0_session/attributes.conf

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Windows Rules https://wiki.hyprland.org/0.45.0/Configuring/Window-Rules/

source = ./floating.conf
source = ./general.conf
source = ./layers.conf
source = ./opacity.conf
