####################################
# 
####################################
#

###
windowrulev2 = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrulev2 = float, class:^(org.gnome.Calculator)$

### FLOATING WINDOW RULES
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = size 800 600, class:^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = center, class:^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = pin, class:^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = animation gnomed, class:^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$

### Media view
windowrulev2 = float, class:^(com.interversehq.qView|mpv)$
windowrulev2 = size 1150 650, class:^(com.interversehq.qView|mpv)$
windowrulev2 = center, class:^(com.interversehq.qView|mpv)$
windowrulev2 = animation popin , class:^(com.interversehq.qView|mpv)$

###
windowrule = float, class:^(qt5ct|qt6ct|nwg-look|nwg-displays|CachyOSHello|org.cachyos.scx-manager|org.cachyos.KernelManager|org.keepassxc.KeePassXC|org.manjaro.pamac.manager|com.github.wwmm.easyeffects)$
windowrule = size 1200 800, class:^(qt5ct|qt6ct|nwg-look|nwg-displays|CachyOSHello|org.cachyos.scx-manager|org.cachyos.KernelManagerorg.keepassxc.KeePassXC|org.manjaro.pamac.manager|com.github.wwmm.easyeffects)$
windowrule = center, class:^(qt5ct|qt6ct|nwg-look|nwg-displays|CachyOSHello|org.cachyos.scx-manager|org.cachyos.KernelManagerorg.keepassxc.KeePassXC|org.manjaro.pamac.manager|com.github.wwmm.easyeffects)$

### PICTURE-IN-PICTURE (PIP) RULES
windowrule = float, title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = pin, title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = size 480 270, title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = move 74.5% 4.25%, title:.*(Picture-in-Picture|Picture in Picture).*
windowrule = animation popin, title:.*(Picture-in-Picture|Picture in Picture).*
