
# # System: Event Management
# windowrule {
#     name = global-suppression
#     match:class = .*
#     suppress_event = maximize
# }

# # Fix: XWayland "Ghost" Windows & Dragging
# windowrule {
#     name = xwayland-fix
#     match:class = ^$
#     match:title = ^$
#     match:xwayland = on
#     match:fullscreen = off
#     match:float =  on
#     match:pin = off



#     focus = off
#     blur = off
# }
