################
#
################

# Decorations related to floating windows on workspaces 1 to 100
windowrulev2 = rounding 10, floating:1, onworkspace:w[fv1-100]

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# No blur for empty class/title
windowrulev2 = noblur,class:^()$,title:^()$
