# Waybar Styling
layerrule {
    name = Waybar
    match:namespace = ^(waybar)$

# https://wiki.hypr.land/0.45.0/Configuring/Window-Rules/#layer-rules

# Rofi Overlay
layerrule {
    name = Rofi
    match:namespace = ^(rofi)$

###
layerrule = blur, vicinae
layerrule = ignorezero, vicinae
layerrule = xray 0, vicinae
layerrule = noanim, vicinae

###
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = xray 0, swaync-control-center
layerrule = noanim, swaync-control-center

# ###
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = xray 0, swaync-notification-window
# layerrule = animation slide down, swaync-notification-window
