####################################
# LAYER RULES
####################################

#https://wiki.hypr.land/0.45.0/Configuring/Window-Rules/#layer-rules

###
layerrule = blur,waybar
layerrule = blurpopups, waybar
layerrule = ignorezero, waybar
layerrule = xray 0,waybar
layerrule = animation slide down, waybar

###
layerrule = blur, vicinae
layerrule = ignorezero, vicinae
# layerrule = xray 0, vicinae
layerrule = noanim, vicinae

###
layerrule = blur,rofi
# layerrule = xray 0,rofi
layerrule = dimaround,rofi
layerrule = ignorezero,rofi
layerrule = ignorealpha 0.9,rofi
layerrule = noanim, rofi

###
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = xray 0, swaync-control-center
layerrule = noanim, swaync-control-center

###
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = xray 0, swaync-notification-window

###
layerrule = blur, logout_dialog
layerrule = xray 0, logout_dialog
layerrule = dimaround, logout_dialog
layerrule = animation gnomed,  logout_dialog
