# Waybar Styling
layerrule {
    name = Waybar
    match:namespace = ^(waybar)$

    blur = on
    blur_popups = on
    ignore_alpha = 0
    xray = off

    animation = slide down
}

# Notification Center (SwayNC)
layerrule {
    name = SwayNC
    match:namespace = ^(swaync-control-center|swaync-notification-window)$

    blur = on
    blur_popups = on
    ignore_alpha = 0
    xray = off

    no_anim = true
}

# vicinae menu
layerrule {
    name = vicinae
    match:namespace = vicinae

    blur = on
    blur_popups = on
    ignore_alpha = 0
    xray = off

    no_anim = true
}

# wlogout
layerrule {
    name = wlogout
    match:namespace = ^(wlogout)$

    blur = on
    blur_popups = on
    ignore_alpha = 0
    xray = off

    animation = fade
}
