#############
# OPACITY WINDOW RULES
############


windowrulev2 = opacity $opacityFloat, class:^(nemo|org.gnome.Nautilus)$
windowrulev2 = opacity $opacityFloat, class:^(discord|armcord|webcord)$
windowrulev2 = opacity $opacityFloat, title:^(QQ|Telegram)$
windowrulev2 = opacity $opacityFloat, class:^(code|cursor)$
