
# Themed Applications Opacity
windowrule {
    name = file-managers-opacity
    match:initial_class = ^(nemo|org.gnome.Nautilus)$
    opacity = $opacityFloat
}

windowrule {
    name = social-apps-opacity
    match:initial_class = ^(discord|armcord|webcord)$
    match:initial_title = ^(Telegram)$ # Combined using OR logic in regex if preferred
    opacity = $opacityFloat
}

windowrule {
    name = editors-opacity
    match:initial_class = ^(code-url-handler|code)$
    opacity = $opacityFloat
}
