[general]
destination = "$HOME/.config/hypr/monitors.conf"


[profiles.portable]
config_file = "/home/rambeau/.config/hyprdynamicmonitors/hyprconfigs/portable.go.tmpl"
config_file_type = "template"
[profiles.portable.conditions]

[[profiles.portable.conditions.required_monitors]]
description = "LG Display 0x06F7"
monitor_tag = "monitor0"



[profiles.station]
config_file = "/home/rambeau/.config/hyprdynamicmonitors/hyprconfigs/station.go.tmpl"
config_file_type = "template"
[profiles.station.conditions]

[[profiles.station.conditions.required_monitors]]
description = "LG Display 0x06F7"
monitor_tag = "monitor0"

[[profiles.station.conditions.required_monitors]]
description = "Huawei Technologies Co. Inc. ZQE-CBA 0xC080F622"
monitor_tag = "monitor1"
