# Ghostty theme generated by Matugen
# Variant: {{mode}}

# Palette 0-7 (standard colors)
palette = 0={{colors.surface.default.hex}}
palette = 1={{colors.error.default.hex}}
palette = 2={{colors.tertiary.default.hex}}
palette = 3={{colors.tertiary.default.hex}}
palette = 4={{colors.primary.default.hex}}
palette = 5={{colors.secondary.default.hex}}
palette = 6={{colors.primary.default.hex}}
palette = 7={{colors.on_surface.default.hex}}

# Palette 8-15 (bright colors)
palette = 8={{colors.surface_variant.default.hex}}
palette = 9={{colors.error_container.default.hex}}
palette = 10={{colors.tertiary_container.default.hex}}
palette = 11={{colors.tertiary_container.default.hex}}
palette = 12={{colors.primary_container.default.hex}}
palette = 13={{colors.secondary_container.default.hex}}
palette = 14={{colors.primary_container.default.hex}}
palette = 15={{colors.on_surface_variant.default.hex}}

# Core theme colors
background = {{colors.surface.default.hex}}
foreground = {{colors.on_surface.default.hex}}
cursor-color = {{colors.primary.default.hex}}
cursor-text = {{colors.on_primary.default.hex}}
selection-background = {{colors.primary_container.default.hex}}
selection-foreground = {{colors.on_primary_container.default.hex}}

# Syntax highlighting accents
# These use the palette indices above for terminal applications
