# TTY 16-color palette generated by Matugen

export COLOR_0="{{colors.background.default.hex}}"            # black
export COLOR_1="{{colors.error.default.hex}}"                 # red
export COLOR_2="{{colors.primary.default.hex}}"               # green
export COLOR_3="{{colors.secondary.default.hex}}"             # yellow
export COLOR_4="{{colors.tertiary.default.hex}}"              # blue
export COLOR_5="{{colors.on_secondary_container.default.hex}}"# magenta
export COLOR_6="{{colors.surface_variant.default.hex}}"       # cyan
export COLOR_7="{{colors.on_background.default.hex}}"         # white

# Bright variants
export COLOR_8="{{colors.surface.default.hex}}"               # bright black
export COLOR_9="{{colors.error.default.hex}}"                 # bright red
export COLOR_10="{{colors.primary.default.hex}}"              # bright green
export COLOR_11="{{colors.secondary.default.hex}}"            # bright yellow
export COLOR_12="{{colors.tertiary.default.hex}}"             # bright blue
export COLOR_13="{{colors.on_secondary_container.default.hex}}" # bright magenta
export COLOR_14="{{colors.surface_container_high.default.hex}}" # bright cyan
export COLOR_15="{{colors.on_background.default.hex}}"        # bright white
