# TTY colors generated by Matugen

COLOR_0={{colors.surface.default.hex}}
COLOR_1={{colors.error.default.hex}}
COLOR_2=#8aac8b
COLOR_3={{colors.tertiary.default.hex}}
COLOR_4={{colors.inverse_primary.default.hex}}
COLOR_5={{colors.outline.default.hex}}
COLOR_6={{colors.primary.default.hex}}
COLOR_7={{colors.on_surface.default.hex}}

# Bright versions
COLOR_8={{colors.surface_variant.default.hex}}
COLOR_9={{colors.error_container.default.hex}}
COLOR_10={{colors.primary_container.default.hex}}
COLOR_11={{colors.tertiary_container.default.hex}}
COLOR_12={{colors.secondary_container.default.hex}}
COLOR_13={{colors.outline_variant.default.hex}}
COLOR_14={{colors.inverse_surface.default.hex}}
COLOR_15={{colors.on_surface_variant.default.hex}}
