#!/bin/bash
# random_wallpaper_hyprpaper.sh
# This script selects a random wallpaper from a folder,
# sets it using hyprpaper (via hyprctl),
# extracts a color palette using pywal,
# and updates configuration files for kitty, GTK, and Qt.

# Set your wallpaper directory and monitor name (adjust as necessary)
WALLPAPER_DIR="$HOME/Wallpapers"
# Replace with your actual monitor name; you can get it with: hyprctl monitors
MONITOR="DP-1"

# Select a random wallpaper (supports jpg and png files)
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) | shuf -n 1)

if [ -z "$WALLPAPER" ]; then
    echo "No wallpaper found in $WALLPAPER_DIR"
    exit 1
fi

echo "Selected wallpaper: $WALLPAPER"

# Set the wallpaper using hyprpaper via hyprctl:
# Preload the wallpaper
hyprctl hyprpaper preload "$WALLPAPER"
# Apply the wallpaper to the specified monitor
hyprctl hyprpaper wallpaper "$MONITOR,$WALLPAPER"

# Extract colors from the wallpaper using pywal:q
wal -i "$WALLPAPER"

# Update kitty theme (if pywal generated a kitty theme file)
if [ -f "$HOME/.cache/wal/kitty.conf" ]; then
    cp "$HOME/.cache/wal/kitty.conf" "$HOME/.config/kitty/kitty_wal_theme.conf"
    # Reload kitty theme in all open kitty windows
    kitty +kitten themes --reload-in=all kitty_wal_theme
fi

# Update GTK theme (if a GTK CSS file was generated by pywal)
if [ -f "$HOME/.cache/wal/colors-gtk.css" ]; then
    cp "$HOME/.cache/wal/colors-gtk.css" "$HOME/.config/gtk-3.0/gtk.css"
fi

# Update Qt theme (if using qt5ct and a config was generated)
if [ -f "$HOME/.cache/wal/qt5ct.conf" ]; then
    cp "$HOME/.cache/wal/qt5ct.conf" "$HOME/.config/qt5ct/qt5ct.conf"
fi

# Optionally reload Hyprland configuration to update any dynamic variables
hyprctl reload

echo "Wallpaper set via hyprpaper and color themes updated."
