############################################################M########################
# basic control features
####################################################################################

#### Pin current window (shows on all workspaces only floating)
bindc = $mainMod, mouse:273, pin
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, mouse:274, togglefloating

#### resizing windows
binde = $mainMod, minus, resizeactive, -20 -10
binde = $mainMod, equal, resizeactive, 20 10

#### close or force close an window
bindd = $mainMod, Q, Closes (not kill) current window, killactive,
bindd = $mainMod $reverse ,Q, Closes (not kill) current window, forcekillactive,

#### Toggles current window fullscreen
bindd = $mainMod, F, mode partial, fullscreen, 1
bindd = $mainMod $reverse, F, mode fully, fullscreen, 0

#### Special workspaces (scratchpads)
bindd = $mainMod, S, Toggles the Special workspace, togglespecialworkspace, special
bindd = $mainMod $reverse, S, Move active window to Special workspace, movetoworkspace,special

#### Grouping Windows
bindd = $mainMod, T, Toggles current window group mode (ungroup all related), togglegroup,
bindd = $mainMod, Tab, Switches to the next window in the group, changegroupactive, f
# bindd = $mainMod $reverse, Tab, Switches to the next previews in the group,





#### replace current with a window open
# bindn = ALT, tab, exec, ~/.config/vicinae/menus/swap_picker.sh

#### switch between windows in a floating workspace
# bind = ALT, Tab, cyclenext, visible # change focus to another window
# bind = ALT, Tab, alterzorder, top # bring it to the top
