####################################################################################
# Shell and command actions
####################################################################################

bindd = $mainMod $reverse, R, Reload/restarts Waybar, exec, ~/.config/hypr/scripts/reset_shell.sh

## lockscreen
bindd = $mainMod, L, Lock the screen, exec, $lockscreen
bindd = $mainMod $reverse, L, Exits Hyprland by terminating the user sessions, exec, loginctl terminate-user ""

## notifications
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod $reverse, N, exec, swaync-client -C


bindd = $mainMod, RETURN, Opens your preferred terminal emulator ($terminal), exec, $terminal

bindr = $mainMod, SPACE, exec, vicinae toggle

bindd = $mainMod, E, Opens your preferred filemanager ($filemanager), exec, $filemanager

# bindd = $mainMod, A, Screen capture selection, exec, $capturing

bind = $mainMod, O, exec, hyprshot -m window -m active --clipboard-only

## toggle
bind = $mainMod, C, exec, vicinae vicinae://extensions/vicinae/clipboard/history

# swww img $(find ~/Pictures/walls -type f | vicinae dmenu -p 'Pick a wallpaper...')
