####################################################################################
# Shell and command actions
####################################################################################

bindd = $mainMod $reverse, R, Reload/restarts Waybar, exec, ~/.config/hypr/scripts/reset_shell.sh

##
bindd = $mainMod, L, Lock the screen, exec, $lockscreen
bindd = $mainMod $reverse, L, Exits Hyprland by terminating the user sessions, exec, loginctl terminate-user ""

## notif
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod $reverse, N, exec, swaync-client -C

##
bindd = $mainMod, RETURN, Opens your preferred terminal emulator ($terminal), exec, $terminal
bindr = $mainMod, SPACE, exec, vicinae toggle
bindd = $mainMod, E, Opens your preferred filemanager ($filemanager), exec, $filemanager
# bindd = $mainMod, A, Screen capture selection, exec, $capturing
