####################################################################################
# Shell and command actions
####################################################################################

##
bindd = $mainMod $reverse, R, Reload/restarts shell, exec, $scriptsDir/reset_shell.sh

##
bindr = $mainMod, SPACE, exec, vicinae toggle
## reverse for launching floating windows

## lockscreen
bindd = $mainMod, L, Lock the screen, exec, $lockscreen
bindd = $mainMod $reverse, L, Power menu, exec, pidof wlogout || wlogout

## notifications
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod $reverse, N, exec, swaync-client -C

##
bindd = $mainMod, RETURN, Terminal, exec, $terminal
# bindd = $mainMod $reverse, RETURN, Terminal, exec, $scriptsDir/floating_run.sh 1000 600 "sleep 1"

##
# bindd = $mainMod, E, Filemanager, exec, $filemanager
bindd = $mainMod $reverse, E, Terminal, exec, $scriptsDir/floating_run.sh 1000 600 $filemanager

##
bind = $mainMod, C, exec, $scriptsDir/ocr_extract.sh
bind = $mainMod $reverse, C, exec, hyprshot -m region --clipboard-only ## needs to be fixed

##
bind = $mainMod, X, exec, vicinae vicinae://extensions/vicinae/clipboard/history
# bind = $mainMod $reverse, X, exec, vicinae vicinae://extensions/vicinae/clipboard/history



## system tuis
bindd = $mainMod, W, Wifi Manager, exec, $scriptsDir/floating_run.sh 1000 600 wifitui
bindd = $mainMod, B, Bluetooth Manager, exec, $scriptsDir/floating_run.sh 1000 600 bluetui
bindd = $mainMod, M, Audio Mixer, exec, $scriptsDir/floating_run.sh 1000 600 wiremix
# bind dynamic displays and profiles menu to super p


## keybind to pop past from clipboard
