####################################################################################
# system control
####################################################################################

### LAPTOP LID SWITCH HANDLING
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable" & hyprctl reload # Lid closed
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, enable" & hyprctl reload # Lid opened
# Note: Remember to modify /etc/systemd/logind.conf before using

### volume control
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% # Lower Volume
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% # Lower Volume
bindel = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle	#Mutes audio
bindel = , XF86AudioMicMute, exec, pactl set-sink-mute @DEFAULT_AUDIO_SOURCE@ toggle

### Playback Control
bindd = , XF86AudioPlay, Toggles play/pause, exec, playerctl play-pause
bindd = , XF86AudioNext, Next track, exec, playerctl next
bindd = , XF86AudioPrev, Previous track, exec, playerctl previous

### brightness control internal and external
bind = , XF86MonBrightnessUp, exec, ddcutil --bus 1 setvcp 10 + 10; brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, ddcutil --bus 1 setvcp 10 - 10; brightnessctl set 5%-
