####################################################################################
#  Window Actions
####################################################################################

### Move focus with mainMod + arrow keys
bindd = $mainMod, left, Move focus to the left, movefocus, l
bindd = $mainMod, right, Move focus to the right, movefocus, r
bindd = $mainMod, up, Move focus upwards, movefocus, u
bindd = $mainMod, down, Move focus downwards, movefocus, d

### Move window towards a direction
bindd = $mainMod $reverse, left, Move active window to the left, movewindoworgroup, l
bindd = $mainMod $reverse, right, Move active window to the right, movewindoworgroup, r
bindd = $mainMod $reverse, up, Move active window upwards, movewindoworgroup, u
bindd = $mainMod $reverse, down, Move active window downwards, movewindoworgroup, d

### Resize window with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow	#Drag window
bindm = $mainMod, mouse:273, resizewindow	#Resize the window towards a direction
