[preferred]
# Use hyprland for everything it supports (Screencast, Shortcuts, etc.)
default=hyprland;gtk
# Explicitly use GTK for the File Picker because Hyprland doesn't have one
org.freedesktop.impl.portal.FileChooser=gtk
