source = ./0_session/attributes.conf

general {
    lock_cmd = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
}

# Stage 1: Dim screen (early warning)
listener {
    timeout = $timeoutDim
    on-timeout = brightnessctl -s set 10% # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r # monitor backlight restore.
}

# Stage 2: Lock screen (security)
listener {
    timeout = $timeoutLock
    on-timeout = $lockscreen # lock screen when timeout has passed
}

# Stage 3: Turn off display (power saving)
# listener {
#     timeout = $timeoutScreen
#     on-timeout = hyprctl dispatch dpms off # screen off when timeout has passed
#     on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected after timeout has fired.
# }

# # Stage 4: Suspend system (maximum power saving)
# listener {
#     timeout = $timeoutSuspend
#     on-timeout = systemctl suspend # suspend pc
# }
