# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ./0_session/startup.conf

source = ./2_keybinds/__CORE__.conf

source = ./1_config/animations.conf
source = ./1_config/decorations.conf
source = ./1_config/input.conf
source = ./1_config/variables.conf

source = ./3_rules/__CORE__.conf

# source = ./1_config/plugins.conf

source = ./monitors.conf


source = /home/rambeau/.config/hypr/noctalia/noctalia-colors.conf
