####################################################################################
#                                                                                  #
####################################################################################

plugin {
    virtual-desktops {
        cycleworkspaces = 0
        rememberlayout = size
        notifyinit = 0
        verbose_logging = 0
    }

    overview {
        panelHeight = 200
        # panelBorderWidth = 1
        onBottom = 1
        workspaceMargin = 20
        # reservedArea = 1
        # workspaceBorderSize = 1
        centerAligned = 1
        # hideBackgroundLayers = 1
        # hideTopLayers = 1
        # hideOverlayLayers = 1
        # hideRealLayers = 1
        drawActiveWorkspace = 1
        # overrideGaps = 1
        # gapsIn = 1
        # gapsOut = 1
        # affectStrut = 1
    }
}

####################################################################################
#                                                                                  #
####################################################################################

#

bind = SUPER, G, overview:toggle, all

####################################################################################

# https://github.com/levnikmyskin/hyprland-virtual-desktops?tab=readme-ov-file

bindd = $mainMod, 1, Switch to vdesk 1, vdesk, 1
bindd = $mainMod, 2, Switch to vdesk 2, vdesk, 2
bindd = $mainMod, 3, Switch to vdesk 3, vdesk, 3
bindd = $mainMod, 4, Switch to vdesk 4, vdesk, 4
bindd = $mainMod, 5, Switch to vdesk 5, vdesk, 5
bindd = $mainMod, 6, Switch to vdesk 6, vdesk, 6
bindd = $mainMod, 7, Switch to vdesk 7, vdesk, 7
bindd = $mainMod, 8, Switch to vdesk 8, vdesk, 8
bindd = $mainMod, 9, Switch to vdesk 9, vdesk, 9

bindd = $mainMod SHIFT, 1, Move window silently to vdesk 1, movetodesksilent, 1
bindd = $mainMod SHIFT, 2, Move window silently to vdesk 2, movetodesksilent, 2
bindd = $mainMod SHIFT, 3, Move window silently to vdesk 3, movetodesksilent, 3
bindd = $mainMod SHIFT, 4, Move window silently to vdesk 4, movetodesksilent, 4
bindd = $mainMod SHIFT, 5, Move window silently to vdesk 5, movetodesksilent, 5
bindd = $mainMod SHIFT, 6, Move window silently to vdesk 6, movetodesksilent, 6
bindd = $mainMod SHIFT, 7, Move window silently to vdesk 7, movetodesksilent, 7
bindd = $mainMod SHIFT, 8, Move window silently to vdesk 8, movetodesksilent, 8
bindd = $mainMod SHIFT, 9, Move window silently to vdesk 9, movetodesksilent, 9

####################################################################################

binde = $mainMod, PAGE_UP, backcyclevdesks
binde = $mainMod, PAGE_DOWN, cyclevdesks

bindde = $mainMod SHIFT, PAGE_UP, Move window and switch to the next workspace, movetoprevdesk
bindde = $mainMod SHIFT, PAGE_DOWN, Move window and switch to the previous workspace, movetonextdesk

####################################################################################
