
[launch]
"arch-update-tray" = "/bin/sh -c "sleep 3 && arch-update --tray""
"btrfs-assistant" = "btrfs-assistant-launcher"
"cartes-geo-handler" = "kde-geo-uri-handler --coordinate-template "https://cartes.app/?geo=<URI>" --query-template "https://cartes.app/?geo=<URI>" --fallback "https://cartes.app""
"com.mitchellh.ghostty" = "/usr/bin/ghostty --gtk-single-instance=true"
"com.stremio.stremio" = "stremio"
"dev.noctalia.Noctalia" = "noctalia --daemon"
"dev.zed.Zed" = "zeditor"
"google-maps-geo-handler" = "kde-geo-uri-handler --coordinate-template "https://www.google.com/maps/@<LAT>,<LON>,<Z>z" --query-template "https://www.google.com/maps/search/<Q>" --fallback "https://www.google.com/maps/""
"openstreetmap-geo-handler" = "kde-geo-uri-handler --coordinate-template "https://www.openstreetmap.org/#map=<Z>/<LAT>/<LON>" --query-template "https://www.openstreetmap.org/search?query=<Q>" --fallback "https://www.openstreetmap.org""
"org.cachyos.KernelManager" = "cachyos-kernel-manager"
"org.cachyos.scx-manager" = "scx-manager"
"org.freedesktop.Xwayland" = "/usr/bin/Xwayland -decorate -displayfd 1"
"org.gnome.FileRoller" = "file-roller"
"org.gnome.Nautilus" = "nautilus --new-window"
"org.gnupg.pinentry-qt" = "/usr/bin/pinentry-qt"
"org.kde.kdeconnect.app" = "kdeconnect-app"
"org.kde.kdeconnect.daemon" = "/usr/bin/kdeconnectd"
"org.kde.kdeconnect.handler" = "kdeconnect-handler"
"org.kde.kdeconnect.nonplasma" = "kdeconnect-indicator"
"org.kde.kdeconnect.sms" = "kdeconnect-sms"
"org.kde.kiod6" = "kiod6"
"org.kde.ksecretd" = "ksecretd"
"org.kde.kwalletd" = "kwalletd6"
"org.openrgb.OpenRGB" = "openrgb"
"org.pwmt.zathura" = "zathura"
"org.pwmt.zathura-pdf-mupdf" = "zathura"
"org.qbittorrent.qBittorrent" = "qbittorrent"
"proton.vpn.app.gtk" = "protonvpn-app"
"user-dirs-update-gtk" = "xdg-user-dirs-gtk-update"
"vicinae-url-handler" = "vicinae"
"wheelmap-geo-handler" = "kde-geo-uri-handler --coordinate-template "https://wheelmap.org/?lat=<LAT>&lon=<LON>" --query-template "https://wheelmap.org/search?q=<Q>" --fallback "https://wheelmap.org""
"zen" = "/opt/zen-browser-bin/zen-bin"
