# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃              MSI HARDWARE SPECIFIC (RTX 3060)               ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# --- MONITOR ---
monitor=eDP-1, 1920x1080@144, 0x0, 1



# --- GPU PRIORITY (NVIDIA First) ---
# Quoted to allow colons in the PCI paths
env = AQ_DRM_DEVICES,"/dev/dri/by-path/pci-0000:01:00.0-card:/dev/dri/by-path/pci-0000:00:02.0-card"

env = MOZ_DISABLE_RDD_SANDBOX,1

# --- NVIDIA SPECIFIC ---
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct

# --- PERFORMANCE ---
# Force Vulkan to use the NVIDIA card
env = __VK_LAYER_NV_optimus,NVIDIA_only
