# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$lockscreen = hyprlock
$idlehandler = hypridle

$notification = swaync -c
$capturing = grim -g "$(slurp)" - | swappy -f -
# $applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
$applauncher = rofi -show drun

$filemanager = nautilus
$terminal = kitty
$browser =
$editor =
