[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "size"
show_hidden    = false
show_symlink   = true
# Enables native drag-and-drop for supported terminals
mouse_events   = [ "click", "scroll", "touch", "move", "drag" ]

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1024
max_height      = 1024
swap_layout     = false
image_filter    = "triangle"
image_quality   = 75

# [opener]
# edit = [
#   { run = '${EDITOR:-vi} "$@"', block = true, desc = "$EDITOR" },
# ]
# play = [
#   { run = 'mpv "$@"', orphan = true, for = "unix" },
# ]
# open = [
#   # orphan = true ensures the GUI app stays open if you close Yazi
#   { run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
# ]

# [open]
# # Rules for which opener to use based on file type
# rules = [
#   { name = "*.json", use = "edit" },
#   { name = "*.toml", use = "edit" },
#   { name = "*.md",   use = "edit" },
#   { name = "*.txt",  use = "edit" },
#   { mime = "text/*", use = "edit" },
#   { mime = "video/*", use = "play" },
#   { mime = "audio/*", use = "play" },
#   { mime = "image/*", use = "open" },
#   # Fallback: Send everything else to the system's default GUI app
#   { name = "*", use = "open" },
# ]

# [plugin]
# # Defines which external tools generate the thumbnails in the preview pane
# preloaders = [
#   { name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
#   { mime = "image/{avif,hei?,jxl,webp}", run = "magick" },
#   { mime = "image/*", run = "image" },
#   { mime = "video/*", run = "video" },
#   { mime = "application/pdf", run = "pdf" },
# ]
# previewers = [
#   { name = "*/", run = "folder", sync = true },
#   { mime = "text/*", run = "code" },
#   { mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
#   { mime = "application/json", run = "json" },
#   { mime = "image/{avif,hei?,jxl,webp}", run = "magick" },
#   { mime = "image/*", run = "image" },
#   { mime = "video/*", run = "video" },
#   { mime = "application/pdf", run = "pdf" },
#   { mime = "application/{zip,gzip,x-tar,x-bzip*,x-7z-compressed,x-rar,x-xz}", run = "archive" },
# ]