# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

source = ./../0_session/attributes.conf

input {
    kb_layout = us
    repeat_rate = 25
    repeat_delay = 250
    follow_mouse = 1
    sensitivity = 0
    scroll_factor = 1
    accel_profile = flat
    resolve_binds_by_sym = 1
}
