####################################################################################
#                                                                                  #
####################################################################################

# https://wiki.hypr.land/Plugins/Using-Plugins/

plugin {
    # virtual-desktops {
    #     cycleworkspaces = 0
    #     rememberlayout = size
    #     notifyinit = 0
    #     verbose_logging = 0
    # }
}
