# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ./../0_session/attributes.conf

# Variables wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/ #
# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#general
general {
    gaps_in = $gapsIn
    gaps_out = $gapsOut
    border_size = $borderSize

    col.active_border = $error
    col.inactive_border = $background

    layout = dwindle # master|dwindle

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#snap
    snap {
    	enabled = true
    }

}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#gestures
gestures {
    #  workspace_swipe = true
    #  workspace_swipe_fingers = 3
     workspace_swipe_distance = 400
     workspace_swipe_min_speed_to_force = 20
     workspace_swipe_create_new = false
}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#group
group {
	col.border_active = $inverse_on_surface
	col.border_inactive = $background
	col.border_locked_active = $inverse_primary
	col.border_locked_inactive = $inverse_surface

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#groupbar
	groupbar {
		font_family = "JetBrainsMono Nerd Font Propo"
		text_color = $inverse_surface
		col.active = $inverse_on_surface
		col.inactive = $background
		col.locked_active = $inverse_primary
		col.locked_inactive = $inverse_surface
	}
}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#misc
misc {
    font_family = "JetBrainsMono Nerd Font Propo"
    splash_font_family = "JetBrainsMono Nerd Font Propo"
    disable_hyprland_logo = true
    col.splash = $background
    background_color = $inverse_surface
    enable_swallow = true
    swallow_regex = ^(cachy-browser|firefox|nautilus|nemo|thunar|btrfs-assistant.)$
    focus_on_activate = false
    vrr = 2
}

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#render
render {
   direct_scanout = true
}

# See https://wiki.hyprland.org/0.45.0/Configuring/Dwindle-Layout/ for more
dwindle {
    special_scale_factor = 0.9
    pseudotile = true
    preserve_split = true
}

# See https://wiki.hyprland.org/0.45.0/Configuring/Master-Layout/ for more
master {
    new_status = master
    special_scale_factor = 0.9
}
