# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$lockscreen = hyprlock
$idlehandler = hypridle

$notification = swaync -c
$capturing = hyprshot
$applauncher = rofi

$filemanager = nautilus
$terminal = kitty
$browser = zen-browser
$editor = code
