# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,10
envd = XCURSOR_SIZE,10
envd = QT_CURSOR_SIZE,10

# nvidia env variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# VA-API hardware video acceleration
env = NVD_BACKEND,direct

# which GPU to use by priority
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card2

# Flickering in Electron / CEF apps native Wayland support
env = ELECTRON_OZONE_PLATFORM_HINT,auto
# # --enable-features=UseOzonePlatform --ozone-platform=wayland <-- launch with this

# multi monitor not working set to 0 to not force linear modifiers on Multi-GPU buffers.
#env = AQ_FORCE_LINEAR_BLIT=0

# For Qt5/Qt6 applications to use qt5ct/qt6ct/gtk3
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
